### ISSUE TITLE
Token balances not showing when re-entering app

### ISSUE THREAD

**Issue by fliebenberg** [DeXter-on-Radix/website#108] opened 2023-09-11 09:40 UTC
When I have been on the app website and logged into my wallet, if I refresh the page my available balances disappears and it wont allow me to trade because it thinks I dont have enough tokens available.
The app needs to check for available balances when the user is logged into their account (could be automatic if the user had logged in before).

**Comment by EvgeniiaVak** [comment] 2023-09-11 10:05
I think this one should be fixed by PRs that are already in review: #91 and #105

**Comment by EvgeniiaVak** [comment] 2023-09-19 07:45
I can't reproduce after the PRs (#91 and #105) are merged, so closing this one, please reopen if you face it again.

**Closed by EvgeniiaVak** 2023-09-19 07:45 UTC
Labels: bug
