### ISSUE TITLE
Account history pagination

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#144] opened 2023-10-02 16:05 UTC
When account history grows it enlogates the page indefinitely, we need to add pagination and maybe always show fixed number of rows to prevent page jumping when clicking from open orders with small number of orders to order history.

**Comment by nguvictor** [comment] 2023-10-05 12:47
@fliebenberg does the sdk provide pagination?

**Comment by fliebenberg** [comment] 2023-10-09 08:17
The response from the API/SDK will limit results to 100. 
If there are more than 100 orders, the result from the API will include a "nextItem" field which you can use as the "startFrom" field in your next query. 
In the SDK, the getAccountOrders function takes an optional "from" parameter, which is the same as the "startFrom" field mentioned above.

**Comment by dcts** [comment] 2024-07-24 20:13
Closing as this is a duplicate of https://github.com/DeXter-on-Radix/website/issues/483

**Closed by dcts** 2024-07-24 20:13 UTC
Labels: enhancement
