### ISSUE TITLE
OrderBook does not un-group correctly

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#337] opened 2024-04-11 16:52 UTC
https://github.com/DeXter-on-Radix/website/assets/27793901/0cc930cd-069d-430b-93ea-a9c2e2594d11

**Comment by dcts** [comment] 2024-04-13 22:16
Duplicate of https://github.com/DeXter-on-Radix/website/issues/282

**Closed** 2024-04-17 07:44 UTC
Labels: bug
